mercure:
    hubs:
        default:
            url: '%env(MERCURE_PUBLISH_URL)%'
            public_url: '%env(MERCURE_PUBLISH_URL)%'
            jwt:
                secret: '%env(MERCURE_PUBLISHER_JWT_KEY)%'
                publish: '*'
