framework:
    workflows:
        video_processing:
            type: 'state_machine'
            initial_marking: queued
            supports:
                - App\Entity\Video
            places:
                - queued
                - processing
                - completed
                - failed
            transitions:
                start_processing:
                    from: queued
                    to: processing
                complete:
                    from: processing
                    to: completed
                fail:
                    from: processing
                    to: failed
